import turtle
def Olympic(radius):
  turtle.showturtle()
  turtle.color("black")
  turtle.circle(radius)
  turtle.color("white")
  turtle.fd(2.5 * radius)
  turtle.color("red")
  turtle.circle(radius)
  turtle.color("white")
  turtle.bk(5 * radius)
  turtle.color("blue")
  turtle.circle(radius)
  turtle.color("white")
  turtle.fd(1.25 * radius)
  turtle.left(90)
  turtle.fd(radius)
  turtle.left(90)
  turtle.color("yellow")
  turtle.circle(radius)
  turtle.color("white")
  turtle.bk(2.5 * radius)
  turtle.color("green")
  turtle.circle(radius)
